application: unhtml
version: 1
runtime: python27
api_version: 1
threadsafe: 1
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: htmlescape.application
libraries:
- name: lxml
  version: latest

